language: java
jdk:
  - oraclejdk8
dist: trusty
addons:
  sonarcloud:
    organization: "15433-github" # 这里为之前在 sonar 项目中的 organization key
    token:
      secure: "7cf2181d74c3963c59d0d54a7100fb3a4d4077bd" # 这里的数据换成在 sonar 里建立的 token
script:
  - sonar-scanner
